window.STEP_ASSETS = [
  {
    "id": "student-master",
    "name": "生徒マスタ",
    "category": "生徒・指導管理",
    "status": "本番",
    "summary": "生徒基本情報・連絡先・在籍情報などの共通マスタ",
    "users": "管理者",
    "github": "",
    "publicUrl": "",
    "storage": "Google Sheet",
    "notes": "各システムの共通生徒マスタ候補"
  },
  {
    "id": "seiseki",
    "name": "スタッフ用アプリ／成績管理",
    "category": "生徒・指導管理",
    "status": "本番",
    "summary": "成績・面談・志望校・受付カード・各種スタッフ機能の入口",
    "users": "管理者・スタッフ",
    "github": "https://github.com/stepkobetsu-hub/seiseki-kanri",
    "publicUrl": "https://stepkobetsu-hub.github.io/seiseki-kanri/",
    "storage": "Google Sheet／Supabase移行中",
    "notes": "受付カード・エントリーシート・面談メモの実体を追加調査"
  },
  {
    "id": "juku-card",
    "name": "受付カード読み取り",
    "category": "生徒・指導管理",
    "status": "要確認",
    "summary": "受付カードOCR・生徒情報取込",
    "users": "管理者・スタッフ",
    "github": "",
    "publicUrl": "",
    "storage": "Google Sheet",
    "notes": "GitHub・公開URLを確認中"
  },
  {
    "id": "past-exams",
    "name": "過去問DB",
    "category": "生徒・指導管理",
    "status": "要確認",
    "summary": "過去問情報の検索・管理",
    "users": "管理者・スタッフ",
    "github": "",
    "publicUrl": "https://script.google.com/macros/s/AKfycbxqxQOmtwe9lfB0Pt7dKzY3mC2sSRRVG9haDTMvOvrzyQNxhOYQLMTbnxAm9Im3LlXj/exec",
    "storage": "Apps Script／保存先不明",
    "notes": "プロジェクトIDと関連Sheetを確認"
  },
  {
    "id": "step-message",
    "name": "STEP配信システム",
    "category": "運営・連絡管理",
    "status": "本番",
    "summary": "保護者・生徒へのメール配信",
    "users": "管理者・スタッフ",
    "github": "https://github.com/stepkobetsu-hub/step-message-center",
    "publicUrl": "https://stepkobetsu-hub.github.io/step-message-center/",
    "storage": "Google Sheet＋Brevo",
    "notes": "共通不達メール追跡を確認中"
  },
  {
    "id": "delivery-failures",
    "name": "不達メール管理",
    "category": "運営・連絡管理",
    "status": "本番",
    "summary": "Brevo不達メールの確認・停止・再開・アーカイブ",
    "users": "管理者・スタッフ",
    "github": "https://github.com/stepkobetsu-hub/student-QR",
    "publicUrl": "https://stepkobetsu-hub.github.io/student-QR/delivery_failures.html?v=575679fd",
    "storage": "Google Sheet＋Brevo",
    "notes": "完全削除の実データテストは未実施"
  },
  {
    "id": "teacher-portal",
    "name": "講師ポータル",
    "category": "講師・勤務管理",
    "status": "本番",
    "summary": "講師向け各種アプリの入口",
    "users": "講師",
    "github": "https://github.com/stepkobetsu-hub/teacher-portal",
    "publicUrl": "https://stepkobetsu-hub.github.io/teacher-portal/",
    "storage": "GitHub Pages",
    "notes": "授業報告・出退くんQR・給与明細等を集約"
  },
  {
    "id": "teacher-master",
    "name": "講師マスター／給与明細",
    "category": "講師・勤務管理",
    "status": "本番",
    "summary": "講師情報・権限・給与明細データ",
    "users": "管理者・講師",
    "github": "",
    "publicUrl": "",
    "storage": "Google Sheet",
    "notes": "給与明細WebアプリのApps ScriptとURLを確認"
  },
  {
    "id": "qr-register",
    "name": "出退くんQR作成",
    "category": "講師・勤務管理",
    "status": "本番",
    "summary": "生徒・講師用QRコード作成・登録",
    "users": "管理者",
    "github": "https://github.com/stepkobetsu-hub/student-QR",
    "publicUrl": "https://stepkobetsu-hub.github.io/student-QR/student_qr_register.html",
    "storage": "Google Sheet＋Apps Script",
    "notes": "生徒・講師の両方を扱う共通基盤"
  },
  {
    "id": "teacher-schedule",
    "name": "講師予定・夏休み出勤登録",
    "category": "講師・勤務管理",
    "status": "本番",
    "summary": "講師の出勤可能日登録・管理・時間割転記",
    "users": "講師・管理者",
    "github": "https://github.com/stepkobetsu-hub/teacher_schedule",
    "publicUrl": "https://stepkobetsu-hub.github.io/teacher_schedule/teacher_app.html",
    "storage": "Supabase＋Google Sheet",
    "notes": "類似Sheet 2件とsummer-teacherの関係を確認"
  },
  {
    "id": "billing",
    "name": "請求管理システム",
    "category": "経理・請求管理",
    "status": "本番要特定",
    "summary": "月謝・講習・教材・模試・割引・CSV出力",
    "users": "管理者",
    "github": "",
    "publicUrl": "https://script.google.com/macros/s/AKfycbxzkE1tQRyB_Ca4bfPKYWIkpTukIVPMWKf2ETE7yN7qROJk0VyOlvxaJ9GGI5p-6pGb/exec",
    "storage": "Google Sheet＋Apps Script",
    "notes": "本番Apps Scriptの対応関係を管理台帳で確認中"
  },
  {
    "id": "contact",
    "name": "お問い合わせ管理",
    "category": "入塾・営業管理",
    "status": "本番",
    "summary": "お問い合わせ受付、自動返信、塾への通知、Google連絡先登録、週次確認",
    "users": "管理者",
    "github": "https://github.com/stepkobetsu-hub/step-form",
    "publicUrl": "https://stepkobetsu-hub.github.io/step-form/contact_form.html",
    "storage": "Google Sheet＋Apps Script＋Gmail＋Google Contacts",
    "notes": "Apps ScriptプロジェクトURLを台帳へ追加する"
  },
  {
    "id": "step-hub",
    "name": "STEP統合管理ポータル",
    "category": "共通基盤",
    "status": "本番",
    "summary": "全システム・Google Sheet・Apps Script・GitHub・公開URLの統合入口",
    "users": "管理者",
    "github": "https://github.com/stepkobetsu-hub/step-hub",
    "publicUrl": "https://stepkobetsu-hub.github.io/step-hub/system/",
    "storage": "GitHub Pages",
    "notes": "この初版をstep-hubへ配置して再利用する想定"
  }
];
